name: Build CPython (Windows)

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: "CPython version to build (e.g. 3.12.15)"
        required: true
        default: "3.12.15"

permissions:
  contents: write

jobs:
  build-python:
    runs-on: windows-latest

    env:
      PY_VER: ${{ inputs.python_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Cache externals
        uses: actions/cache@v6
        with:
          path: Python-${{ env.PY_VER }}/PCbuild/externals
          key: cpython-externals-${{ env.PY_VER }}

      - name: Download and extract source
        shell: pwsh
        run: |
          $tarFile = "Python-$env:PY_VER.tgz"
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/$env:PY_VER/$tarFile" -OutFile $tarFile
          tar -xf $tarFile

      - name: Prepare external dependencies
        shell: cmd
        run: |
          cd Python-%PY_VER%\PCbuild
          call get_externals.bat

      - name: Install Release Prerequisites
        shell: pwsh
        run: |
          python -m pip install sphinx blurb

      - name: Build CPython (Release x64 with PGO)
        shell: cmd
        run: |
          cd Python-%PY_VER%
          set PlatformToolset=v145
          set CL=/MP
          call Tools\msi\buildrelease.bat -x64 --pgo

      - name: SSH Debug
        uses: owenthereal/action-upterm@v2
        if: ${{ failure() }}
        with:
          authorized_keys: |
            ssh-ed25519 "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPdPBTPQcZFps6FWf58gzrO10IDOa33X8+V/3LsYbOV @jenking"

      - name: Prepare Output & Hashes
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output -Force
          Copy-Item "Python-$env:PY_VER\PCbuild\amd64\en-us\python-$env:PY_VER-*" output\ -Force
          Get-FileHash output\*.exe, output\*.msi -Algorithm SHA256 | ForEach-Object { "$($_.Hash)  $($_.FileName)" } > output\SHA256SUMS.txt
          "RELEASE_SHA256=$((Get-FileHash output\python-$env:PY_VER-amd64.exe).Hash)" >> $env:GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cpython-${{ env.PY_VER }}-release
          path: output/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.PY_VER }}-win64
          name: CPython ${{ env.PY_VER }} Windows x64 Release
          body: |
            CPython ${{ env.PY_VER }} Windows x64 Release build.

            SHA256 (exe):
            ${{ env.RELEASE_SHA256 }}

            Files:
            - python-${{ env.PY_VER }}-amd64.exe
            - python-${{ env.PY_VER }}-embed-amd64.zip
            - SHA256SUMS.txt
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
